Error alerting
broadinstitute/seqr pull request #1504
Opened 2020-11-16 20:25 UTC by hanars

Since we now alert on all logged errors, this cleans up some error handling

2020-11-16 20:26 UTC, hanars commented on seqr/utils/elasticsearch/es_search.py
> +            from seqr.utils.elasticsearch.utils import InvalidSearchException
this file can't be imported at the top of the file due to circular import issues

2020-11-16 23:37 UTC, hanars commented
codacy (errors are okay to ignore): https://app.codacy.com/gh/macarthur-lab/seqr/pullRequest?prid=6517032

2020-11-17 16:07 UTC, hanars commented
passing tests: https://travis-ci.org/github/broadinstitute/seqr/builds/744064817

2020-11-18 02:17 UTC, ShifaSZ requested changes

2020-11-18 02:17 UTC, ShifaSZ commented on seqr/views/utils/pedigree_image_utils_tests.py
> +        mock_logger.error.reset_mock()
These two lines can be `mock_logger.reset_mock()`.

2020-11-19 17:21 UTC, hanars commented on seqr/utils/elasticsearch/es_search.py
> +            from seqr.utils.elasticsearch.utils import InvalidSearchException
Nope, it just makes a circular dependency elsewhere :(

2020-11-19 18:36 UTC, ShifaSZ approved these changes

2020-11-19 19:38 UTC, merged