Case review updates
broadinstitute/seqr pull request #1528
Opened 2020-12-02 17:10 UTC by hanars

We have one seqr project that we run out of our lab where we have special functionality for doing case review. Currently, we permission this view by making it available to staff users in all projects, and then  the users just don't use it in all the unnecessary projects. Many of the users who use case review are people who only need access to the one project they review, but because the only way to access case review is as a staff user, they are granted staff access to all projects, which is not great. This changes the permissioning such that case review is enabled on a per project basis, and managers of that project will be able to access case review

2020-12-02 19:27 UTC, hanars commented
passing tests: https://travis-ci.org/github/broadinstitute/seqr/builds/747244249

2020-12-03 15:33 UTC, ShifaSZ requested changes
There may be some minor coding style issues.

2020-12-03 15:33 UTC, ShifaSZ commented on seqr/views/utils/orm_to_json_utils.py
> +    return _get_json_for_models(families, user=user, process_result=_process_result,  **kwargs)
An extra blank is added before `**kwargs`

2020-12-03 15:33 UTC, ShifaSZ commented on seqr/views/utils/orm_to_json_utils.py
> +        kwargs['additional_model_fields'] = (kwargs['additional_model_fields'] or []) + ['project_id']
Using `kwargs['additional_model_fields'].append('project_id')` as the code for the individual looks nicer.

2020-12-03 15:33 UTC, ShifaSZ commented on seqr/views/utils/orm_to_json_utils.py
> +        return None
It seems that returning `[]` is better than returning `None`.

2020-12-03 15:33 UTC, ShifaSZ commented on seqr/views/utils/orm_to_json_utils.py
> +        'additional_model_fields': _get_case_review_fields(individuals[0], individuals[0].family.project, user) or []
`or []` can be removed if `_get_case_review_fields()` return `[]` when there is no permission.

2020-12-04 19:49 UTC, ShifaSZ approved these changes

2020-12-07 15:52 UTC, hanars commented
passing tests: https://travis-ci.org/github/broadinstitute/seqr/builds/747691119

2020-12-07 15:52 UTC, merged