Anvil tweaks
broadinstitute/seqr pull request #1696
Opened 2021-03-02 22:53 UTC by hanars

Fixes email to send as actual HTML, and disables adding collaborators for AnVIl projects. While we need to keep user management for editing and removing users, one a project has been linked to AnVIL the only way to grant acccess must be through AnVIL itself

2021-03-03 16:12 UTC, hanars commented
codacy error okay to ignore

2021-03-03 19:04 UTC, ShifaSZ requested changes
Nice updates to the coding and the UI. There are two trivial comments.

2021-03-03 22:26 UTC, hanars commented on seqr/views/utils/orm_to_json_utils.py
> +                continue
added

2021-03-04 17:19 UTC, ShifaSZ approved these changes

2021-03-04 17:25 UTC, merged