Pm permission to update igv
broadinstitute/seqr pull request #1730
Opened 2021-03-16 22:06 UTC by hanars

Grants PMs permission to update IGV. Moves the relevent functions out of dataset_api.py into the more pertinent igv_api.py

2021-03-16 22:07 UTC, hanars commented on seqr/views/apis/dataset_api.py
> -@data_manager_required
all copy-pasted to igv_api.py

2021-03-16 22:07 UTC, hanars commented on seqr/views/apis/igv_api.py
unless noted otherwise, everything is copy-paste

2021-03-16 22:07 UTC, hanars commented on seqr/views/apis/igv_api.py
> +@pm_or_data_manager_required
this is the real thing that changed - checks if user is either PM or data manager

2021-03-16 22:08 UTC, hanars commented on seqr/views/apis/igv_api.py
> +@pm_or_data_manager_required
changed permission check

2021-03-16 22:08 UTC, hanars commented on seqr/views/apis/igv_api.py
> +        if not does_file_exist(file_path):
changed this to directly check the file here (used to have a helper method but that didn't hep much)

2021-03-17 16:14 UTC, ShifaSZ requested changes
There are some CI tests failed.

2021-03-17 19:45 UTC, ShifaSZ approved these changes

2021-03-17 20:05 UTC, merged