Allow users to edit name
broadinstitute/seqr pull request #1775
Opened 2021-03-31 21:43 UTC by hanars

2021-04-01 20:58 UTC, ShifaSZ requested changes

2021-04-01 21:01 UTC, hanars commented on seqr/views/apis/users_api.py
> +def update_user(request):
I am happy to hold off on merging this until that PR is merged and then resolving any issues, or merging this one and resolving the issues on that PR. Unit tests will fail if this doesn't get updated correctly so theres no risk of something slipping, and so I'm happy to go in which ever order you approve

2021-04-01 21:22 UTC, hanars commented on seqr/views/apis/users_api.py
> +def update_user(request):
the other PR is merged so this is resolved

2021-04-02 13:24 UTC, ShifaSZ approved these changes

2021-04-02 14:35 UTC, merged