Bulk individual update
broadinstitute/seqr pull request #1796
Opened 2021-04-16 15:23 UTC by hanars

Add more requested fields for manager-level users to bulk upload

2021-04-19 15:23 UTC, ShifaSZ requested changes

2021-04-19 15:23 UTC, ShifaSZ commented on seqr/views/apis/individual_api_tests.py
> +        url = reverse(receive_individuals_metadata_handler, args=['R0001_1kg'])
Change the test function name as well?

2021-04-20 15:02 UTC, hanars commented on seqr/views/apis/individual_api.py
> +AR_DSPERM_COL = 'ar_donorsperm'
it stands for "assisted reproduction" but we use this abbreviation in all the model field names in seqr so I'm not sure a comment is necessary here, but I can add one

2021-04-20 15:51 UTC, ShifaSZ approved these changes

2021-04-20 16:30 UTC, merged