Add retries to gcloud cli auth configuration
broadinstitute/seqr pull request #2472
Opened 2022-02-14 18:00 UTC by sjahl

2022-02-14 19:08 UTC, sjahl commented
Closes #2437

2022-02-14 19:10 UTC, sjahl commented on settings.py
> +                                           capture_output=True, text=True).stderr)[0] # nosec
i had to add the `# nosec` here to pass codacy. It initially complained about the use of `shell=True`, which i thought was reasonable. But, after doing what I thought it wanted, and using a `shell=False`, it complained about unsanitized command input... but the input here is a static list. Let me know if you have any thoughts on this (or thoughts on how to improve the logic in this section in general, @hanars )

2022-02-14 20:12 UTC, hanars requested changes

2022-02-14 22:19 UTC, hanars requested changes

2022-02-14 22:19 UTC, hanars commented on CHANGELOG.md
> +* Adds NPM asset build to the seqr dockerfile
I think this was an error and meant as part of a different PR?

2022-02-14 23:20 UTC, sjahl commented
Whoops, yeah, forgot to switch branches!

On Mon, Feb 14, 2022 at 5:19 PM hanars ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In CHANGELOG.md
> <https://github.com/broadinstitute/seqr/pull/2472#discussion_r806285678>:
>
> > @@ -2,6 +2,9 @@
>
>  ## dev
>
> +* Update seqr dockerfile to improve immutability and build automation (REQUIRES IMAGE UPDATE)
> +* Adds NPM asset build to the seqr dockerfile
>
> I think this was an error and meant as part of a different PR?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/broadinstitute/seqr/pull/2472#pullrequestreview-882253683>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAE3OD4I7GZMLGEZZXL6WCTU3F5YXANCNFSM5OMFJ3JA>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2022-02-15 16:35 UTC, hanars approved these changes

2022-02-15 19:05 UTC, merged