add size sort
broadinstitute/seqr pull request #2531
Opened 2022-03-09 16:23 UTC by hanars

2022-03-09 20:25 UTC, ShifaSZ requested changes

2022-03-09 21:00 UTC, hanars commented on seqr/utils/elasticsearch/constants.py
> +               'source': "doc['start'].value - doc['end'].value"
yes, the negative values cause it to sort in the correct direction. And its biologically/ physically impossible for a single SV to span multiple chromosomes

2022-03-09 22:07 UTC, ShifaSZ commented on seqr/utils/elasticsearch/constants.py
> +               'source': "doc['start'].value - doc['end'].value"
The translocation SVs can move from one chromosome to another one. We can find many translocation SVs have a different CHR2 from their contig.

2022-03-09 22:18 UTC, hanars commented on seqr/utils/elasticsearch/constants.py
> +               'source': "doc['start'].value - doc['end'].value"
A transloacation that moves from one chromosome to another os not the "size" of the distance between chromosomes, its the size of whatever element was moved. This is the computation we use when we display translocations to users and noone has commented that its looks wrong. Moreover, we want the sort to correspond to whats displayed so it looks logical

2022-03-10 14:10 UTC, ShifaSZ commented on seqr/utils/elasticsearch/constants.py
> +               'source': "doc['start'].value - doc['end'].value"
It seems that the information of a translocation SV is insufficient for its "size". We use the below code to generate the `end` field in the genome SV loading pipeline. And the END2 is just the breaking point on the second chromosome.
```
hl.if_else(hl.is_defined(rows.info.END2), rows.info.END2, rows.info.END)
```

2022-03-10 14:49 UTC, hanars commented on seqr/utils/elasticsearch/constants.py
> +               'source': "doc['start'].value - doc['end'].value"
this is the size we use for display. this is the size we will be using for sort. this is not negotiable

2022-03-10 15:09 UTC, ShifaSZ commented on seqr/utils/elasticsearch/constants.py
> +               'source': "doc['start'].value - doc['end'].value"
We can go ahead with this issue. It also will be better for us to give the analysts a heads up.

2022-03-10 15:23 UTC, merged