Analyzed by data type
broadinstitute/seqr pull request #2650
Opened 2022-04-12 18:34 UTC by hanars

2022-04-15 07:14 UTC, ShifaSZ requested changes

2022-04-15 07:14 UTC, ShifaSZ commented on ui/shared/components/panel/family/FamilyFields.jsx
> +  return ANALYSED_BY_TYPES.map(typeConfig => (
It can be more readable if replace `typeConfig` with `([type, value])`.

2022-04-15 15:48 UTC, hanars commented on seqr/views/apis/family_api_tests.py
> +        self.assertEqual(response_json[FAMILY_GUID]['analysedBy'][1]['dataType'], 'SV')
this is the created model. I'm not testing the model that already existed

2022-04-15 20:26 UTC, hanars commented
@ShifaSZ I realized my initial PR missed a key feature requested in the ticket, so this is now updated to include the ability to bulk update familys that were analaysed to support tracking analysis that happens outside of seqr

2022-04-16 12:31 UTC, ShifaSZ approved these changes

2022-04-19 15:05 UTC, merged