Variant rna seq performance
broadinstitute/seqr pull request #2687
Opened 2022-04-27 19:55 UTC by hanars

Fetching the RNA TPM data for all the saved variants for large projects takes about a full minute. Rather than fetching the data with the variants, we should instead just indicate if a family has data or not, and then fetch it dynamically when the user actually wants to view the data

2022-04-27 19:57 UTC, hanars commented on ui/shared/components/panel/variants/RnaSeqTpm.jsx
> +const launchGtex = (geneId, familyGuid) => (gencodeId) => {
the control flow changes here - before we already had the sample specific data so we formatted that data and fetched the gtex and rdg aggregate data. Now, we first do one request to fetch the sample and rdg aggregate data, and then do a followup request to gtex for the tissues that are returned from the API

2022-04-28 12:51 UTC, ShifaSZ requested changes
Good PR. I only have two naming comments.

2022-04-28 12:51 UTC, ShifaSZ commented on ui/shared/components/panel/variants/VariantGene.jsx
> +  rnaSeqData: getRnaSeqOutilerDataByFamilyGene(state)[ownProps.variant.familyGuids[0]],
Do you also want to change the `rnaSeqData` to `rnaSeqOutilerData`?

2022-04-29 12:01 UTC, ShifaSZ approved these changes

2022-04-29 18:54 UTC, merged