Loading request airtable tracking
broadinstitute/seqr pull request #2794
Opened 2022-06-22 18:49 UTC by hanars

2022-06-23 19:41 UTC, hanars commented
Note: hold off on merging until move to the correct base

2022-06-27 14:09 UTC, ShifaSZ requested changes

2022-06-27 14:09 UTC, ShifaSZ commented on seqr/views/apis/anvil_workspace_api_tests.py
> +            'AnVIL Project URL': f'http://testserver/project/{project2.guid}/project_page',
As above.

2022-06-27 18:44 UTC, hanars commented on seqr/views/apis/anvil_workspace_api_tests.py
> +            'AnVIL Project URL': f'http://testserver/project/{project.guid}/project_page',
this is consistant with the existing usage in the test (`project.guid` is used a few times in this code here), so its out of scope to change this

2022-06-27 18:44 UTC, hanars commented on seqr/views/apis/anvil_workspace_api_tests.py
> +            'AnVIL Project URL': f'http://testserver/project/{project2.guid}/project_page',
same reply as above

2022-06-28 15:43 UTC, ShifaSZ approved these changes

2022-06-28 17:38 UTC, merged