Single genome build search
broadinstitute/seqr pull request #2835
Opened 2022-07-14 21:00 UTC by hanars

2022-07-15 21:37 UTC, ShifaSZ requested changes
Mostly looks very good to me.

2022-07-15 21:37 UTC, ShifaSZ commented on ui/pages/Report/components/CustomSearch.jsx
> +    { value: '', text: 'Custom', color: 'grey' },
`Custom` is obscure. How about `Single Project Search` or others?

2022-07-18 13:52 UTC, hanars commented on ui/pages/Report/components/CustomSearch.jsx
> +const INCLUDE_ALL_PROJECTS = 'allGenomeProjectFamilies'
No

2022-07-19 14:09 UTC, ShifaSZ approved these changes
Excellent work!

2022-07-19 15:24 UTC, merged