Typecheck dev
broadinstitute/seqr pull request #2974
Opened 2022-09-25 22:45 UTC by imteazs

Adding type checking to python code.

2022-09-28 18:25 UTC, hanars requested changes

2022-09-28 18:25 UTC, hanars commented on seqr/utils/logging_utils.py
> +    def __init__(self, name: Optional[str]=None) -> None:
According to PEP8, you need to add spaces around the equals signs now that you have added annotations: https://peps.python.org/pep-0008/#other-recommendations

> Don’t use spaces around the = sign when used to indicate a keyword argument, or when used to indicate a default value for an unannotated function parameter:
When combining an argument annotation with a default value, however, do use spaces around the = sign

2022-09-29 17:58 UTC, hanars requested changes

2022-09-29 17:58 UTC, hanars commented on seqr/views/utils/permissions_utils.py
> -
I think this a merge error

2022-09-29 17:58 UTC, hanars commented on seqr/views/utils/permissions_utils.py
> +def _current_policies_required(view_func: Callable, policy_url: str=API_POLICY_REQUIRED_URL) -> Callable:
still missing spacing here, but otherwise looks good!

2022-10-02 02:45 UTC, imteazs commented
I might have accidentally overwrote my original work while trying to sync new changes, luckily I think I was able recreate them from monkeytype traces.

2022-10-03 15:17 UTC, merged