Refseq transcripts
broadinstitute/seqr pull request #3039
Opened 2022-11-02 19:45 UTC by hanars

2022-11-02 19:45 UTC, hanars commented on reference_data/management/commands/update_gencode.py
> -def _get_valid_gencode_gtf_paths(gencode_release, gencode_gtf_path, genome_version):
moved to utility method

2022-11-02 19:47 UTC, hanars commented on reference_data/management/commands/update_gencode.py
> -def _parse_line(line, i, new_genes, new_transcripts,  existing_gene_ids, existing_transcript_ids, counters, genome_version, gencode_release):
moved to utility method

2022-11-02 19:47 UTC, hanars commented on reference_data/management/commands/update_gencode.py
> +    new_genes, new_transcripts, counters = load_gencode_records(
moved to utility method

2022-11-02 19:48 UTC, hanars commented on reference_data/management/commands/utils/gencode_utils.py
> +def _get_valid_gencode_gtf_paths(gencode_release, gencode_gtf_path, genome_version):
copy pasted from `update_gencode`, does not need review

2022-11-02 19:51 UTC, hanars commented on reference_data/management/commands/utils/gencode_utils.py
> +def _parse_line(line, i, new_genes, new_transcripts,  existing_gene_ids, existing_transcript_ids, counters, genome_version, gencode_release):
copied form `update_gencode`, does not need review unless noted otherwise

2022-11-02 19:51 UTC, hanars commented on reference_data/management/commands/utils/gencode_utils.py
> +        if k == 'tag':
this changed to properly store all tags as a list

2022-11-02 19:51 UTC, hanars commented on reference_data/management/commands/utils/gencode_utils.py
> +        if 'MANE_Select' in record.get('tag', []):
this is new

2022-11-04 15:04 UTC, ShifaSZ requested changes

2022-11-04 15:49 UTC, hanars commented on reference_data/management/commands/update_gencode_transcripts.py
> +        create_transcript_info(new_transcripts)
Not really, I'm pretty sure I've abstracted out all the logic we want to use here, so all the code left here is different than that in `update_gencode`. What part of this code do you think could be reused from `update_gencode` without breaking behavior?

2022-11-04 15:50 UTC, hanars commented on reference_data/management/tests/update_gencode_tests.py
> +            gtf_content = f.read()
this is copy-pasted from a different test function. I can abstract it into a helper, but changing the behavior is out of scope

2022-11-04 15:52 UTC, hanars commented on reference_data/management/tests/update_gencode_tests.py
> +        mock_tempfile.gettempdir.return_value = tmp_dir
This is the behavior for every test in this file. Maybe its not an ideal way of doing things, but it is way out of scope to redo the way mocking works in every test in a test file in order to add one part of one test

2022-11-04 18:08 UTC, ShifaSZ approved these changes

2022-11-04 18:40 UTC, merged