Overview  UI performance
broadinstitute/seqr pull request #3140
Opened 2023-01-05 20:18 UTC by hanars

Data for the project page is loaded in several separate requests. This was badly impacting the preformanceof the project page, as when each request completed any component that had the current project as a prop re-rendered. There were 3 categories of changes I made to address this:
1) Change the response from the server to remove the `<families/overview/etc>Loaded` field from the project response, and instead keep track of which entities have been loaded directly in the state, removing unnecessary updates to the project object
2) Instead of connecting several props to a top level component to pass down to its children, connecting the children directly and removing props from the parent, so when a part of the data updates only the relevant child component updates (i.e. instead of connecting the tag type counts to the top level project page, connect them directly to the tag summary component)
3) Instead of using the full project as a prop, only pass through the fields actually used by the relevant component.

2023-01-06 18:12 UTC, ShifaSZ requested changes

2023-01-06 18:16 UTC, hanars commented on ui/pages/Project/components/ProjectCollaborators.jsx
> +  addCollaborator,
I added log statements for when this component was rendering and before this change it re-rendered when the project's locus lists were updated and after this change it didn't. So I don't know if react.memo is being more clever with prop comparison then just reference, but I am 100% confidant that this change improves performance

2023-01-06 18:17 UTC, hanars commented on ui/pages/Project/components/ProjectOverview.jsx
> +const MatchmakerOverview = React.memo(({ name, mmeSubmissionCount, mmeDeletedSubmissionCount, canEdit }) => (
per above, I explicitly tested the performance updates I was making, I didn't just like get an idea and implement it without bothering to see if it did anything. Every single change in this PR was confirmed to have a performance impact

2023-01-06 18:18 UTC, hanars commented on ui/pages/Project/components/ProjectOverview.jsx
> +  canEdit, hasCaseReview, isAnalystProject, mmeSubmissionCount, mmeDeletedSubmissionCount,
no. 6 renders on page load for one component is not worth it, even if the rendering component is not that big

2023-01-09 16:04 UTC, ShifaSZ commented on ui/pages/Project/components/ProjectCollaborators.jsx
> +  addCollaborator,
It makes sense. Passing the whole `project` needs more re-rendering and impacts the performance. I thought it was the data-maintaining costing the performance.

2023-01-09 16:06 UTC, ShifaSZ commented on ui/pages/Project/components/ProjectOverview.jsx
> +    name,
You may want to change the `name` to `projectName`.

2023-01-09 16:17 UTC, ShifaSZ approved these changes
Great changes.

2023-01-09 16:41 UTC, merged