Shared search data type filtering
broadinstitute/seqr pull request #3390
Opened 2023-05-19 18:28 UTC by hanars

2023-05-22 15:04 UTC, ShifaSZ requested changes
Mostly looks great.

2023-05-22 15:11 UTC, hanars commented on seqr/utils/search/elasticsearch/es_search.py
> +            comp_het_dataset_type = None
Theres a key difference between "a specific data type for the main annotation, but all data types for the secondary annotation" and "a specific data type for the main annotation,  and nothing added for the secondary annotation so we use the main annotations and their datatype". Setting it to None makes it impossible to know which of these cases it was. I actually added unit tests for both these cases, implementing your proposed change causes one to fail

2023-05-22 16:10 UTC, hanars commented on seqr/utils/search/elasticsearch/es_search.py
> +            comp_het_dataset_type = None
oh hmm I see your point, I was thinking that secondary dataset type can be specific when the main dataset type is all, which is true, but in that case the comp_het_dataset_type is still None. I will make the update and add a unit test for this case

2023-05-23 15:02 UTC, ShifaSZ approved these changes

2023-05-23 15:34 UTC, merged